services:
  - type: web
    name: crimenet
    runtime: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn --chdir . visualizer.wsgi:server --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
